name: CI/CD for Recipe Finder

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_SECRET_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USERNAME  }}
        run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/
            touch IMANEWFILE.txt '            
